### ISSUE TITLE
Godot build fails with import errors

### ISSUE THREAD

**Issue by seek-dev** [ShadowBlip/opengamepad-ui#2]
Per #1

Building fails and throws a ton of errors using either the Makefile or directly invoking a headless godot build.

Building on the target machine (Steam Deck) over ssh.  Using newest Godot4 beta6 from AUR.  Gamescope installed via pacman.  Freshly cloned main branch as working directory.

Minor issue, but Makefile uses non-standard fixed paths to godot4 and gamescope binaries, so those needed to be modified to use system paths.

building invoked using both `make build` and directly using `godot4 --headless --export "Linux"` (per godot4 documentation) as well as trying `godot4 --headless --export "Linux/X11"`.  Seems to be the same issues in any case.

[build.log via Makefile](https://github.com/ShadowBlip/opengamepad-ui/files/10098759/build.log)

Was only able to get it to build after repeatedly opening the project in the GUI editor :P

**Comment by ShadowApex** [comment]
It looks like this is currently an open issue: https://github.com/godotengine/godot/pull/68461

One option would be to commit the `.godot` converted assets, but would increase the repo size. If you run `godot4 --headless --editor .`, it should convert the assets. I'll add it to the Makefile to do it automatically if `.godot` doesn't exist, along with updating the paths to their standard form.

**Comment by ShadowApex** [comment]
I've updated the Makefile in this commit: https://github.com/ShadowBlip/opengamepad-ui/commit/1e26c34249feb4d50cffcfd700d5c4b1269048dd

It's a bit of a hack until Godot implements a `--import` flag to handle this better. Or if it's a problem, I can bite the bullet and commit the imported assets.
